## Exercise from yesterday

In [3]:
# Input file and containers to store data
f = open('../../data/WaveData.csv', 'r')
features = []
waves = []

# Loop over the lines
for l in f:
    
    # Initialize the container for one wave
    w = {}
    
    # Clean the line and get each field
    values = l.strip().split(',')
    
    # Get the first line as being all the features
    if values[0] == 'Date/Time':
        features = values
    
    # Get the other line as data, as float except for the data
    else:
        for i, feat in enumerate(features):
            w[feat] = values[i]
        if feat != 'Date/Time':
                w[feat] = float(w[feat])
        waves.append(w)

In [4]:
waves

[{'Date/Time': '01/01/2017 00:00',
  'Hs': '-99.9',
  'Hmax': '-99.9',
  'Tz': '-99.9',
  'Tp': '-99.9',
  'Peak Direction': '-99.9',
  'SST': -99.9},
 {'Date/Time': '01/01/2017 00:30',
  'Hs': '0.875',
  'Hmax': '1.39',
  'Tz': '4.421',
  'Tp': '4.506',
  'Peak Direction': '-99.9',
  'SST': -99.9},
 {'Date/Time': '01/01/2017 01:00',
  'Hs': '0.763',
  'Hmax': '1.15',
  'Tz': '4.52',
  'Tp': '5.513',
  'Peak Direction': '49',
  'SST': 25.65},
 {'Date/Time': '01/01/2017 01:30',
  'Hs': '0.77',
  'Hmax': '1.41',
  'Tz': '4.582',
  'Tp': '5.647',
  'Peak Direction': '75',
  'SST': 25.5},
 {'Date/Time': '01/01/2017 02:00',
  'Hs': '0.747',
  'Hmax': '1.16',
  'Tz': '4.515',
  'Tp': '5.083',
  'Peak Direction': '91',
  'SST': 25.45},
 {'Date/Time': '01/01/2017 02:30',
  'Hs': '0.718',
  'Hmax': '1.61',
  'Tz': '4.614',
  'Tp': '6.181',
  'Peak Direction': '68',
  'SST': 25.45},
 {'Date/Time': '01/01/2017 03:00',
  'Hs': '0.707',
  'Hmax': '1.34',
  'Tz': '4.568',
  'Tp': '4.705',
  'Peak Di

In [5]:
Data = {}
for feat in features[1:]:
    Data[feat] = []
    for w in waves:
        Data[feat].append(float(w[feat]))

In [7]:
for k, v in Data.items():
    print(k, v[:5])

Hs [-99.9, 0.875, 0.763, 0.77, 0.747]
Hmax [-99.9, 1.39, 1.15, 1.41, 1.16]
Tz [-99.9, 4.421, 4.52, 4.582, 4.515]
Tp [-99.9, 4.506, 5.513, 5.647, 5.083]
Peak Direction [-99.9, -99.9, 49.0, 75.0, 91.0]
SST [-99.9, -99.9, 25.65, 25.5, 25.45]


### Questions
 + how many corrupted waves
 + compute and print the mean and RMS of each features
 
### Correction

In [9]:
# Total number of waves
Ntot = len(Data[features[1]])

# Loop over waves
Ncorr = 0
for iw in range(Ntot):
    for feat in features[1:]:
        if Data[feat][iw] < -99:
            Ncorr += 1
            break

print(Ncorr, Ntot, Ncorr/Ntot*100)

274 43728 0.6266008049762166


In [10]:
# Define containers to store the result
# k:v -> k: feature, v: rms or mean
rms, mean = {}, {}

def get_mean(Xs):
    res, ntot = 0, len(Xs)
    for x in Xs:
        res += x/ntot
    return res
    
def get_rms(Xs):
    Xmean = get_mean(Xs)
    dX2 = [(x-Xmean)**2 for x in Xs]
    return get_mean(dX2)**0.5
    

# Loop over features
for feat, values in Data.items():
    rms[feat] = get_rms(values)
    mean[feat] = get_mean(values)

In [11]:
for feat in Data.keys():
    print(f'{feat} : {mean[feat]:.2f} +/- {rms[feat]:.2f}')

Hs : 1.04 +/- 4.49
Hmax : 1.89 +/- 4.58
Tz : 5.41 +/- 4.74
Tp : 8.79 +/- 5.36
Peak Direction : 97.40 +/- 28.78
SST : 23.21 +/- 9.81


## NumPy  lecture

In [12]:
import numpy as np

In [13]:
l1, l2 = [1, 2, 3], [3, 4, 5]
a1, a2 = np.array([1, 2, 3]), np.array([3, 4, 5])
print(l1, l2)
print(a1, a2)

[1, 2, 3] [3, 4, 5]
[1 2 3] [3 4 5]


In [14]:
print(l1+l2)

[1, 2, 3, 3, 4, 5]


In [15]:
print(a1+a2)

[4 6 8]


In [16]:
print(l1-l2)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [17]:
print(a1-a2)

[-2 -2 -2]


In [19]:
# Acessing elements

print(l1[1], a1[1])

2 2


In [20]:
print(l1[1:], a1[1:])

[2, 3] [2 3]


In [21]:
idx = [0, 2, 1, 0, 2]
print(a1[idx])

[1 3 2 1 3]


In [22]:
print(l1[idx])

TypeError: list indices must be integers or slices, not list

In [23]:
points = np.array([[ 0,  1, 2],
                   [ 3,  4, 5]])

print('a.dtype = {}'.format(points.dtype))
print('a.shape = {}'.format(points.shape))
print('a.size  = {}'.format(points.size))
print('a.ndim  = {}'.format(points.ndim))

a.dtype = int64
a.shape = (2, 3)
a.size  = 6
a.ndim  = 2


## Vectorization

In [24]:
# Vectorization
a = np.random.randint(low=1, high=100, size=100000)

def explicit_loop_for_inverse(array):
    res = []
    for a in array:
        res.append(1./a)
    return np.array(res)

In [26]:
%timeit explicit_loop_for_inverse(a)

175 ms ± 2.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
%timeit 1/a

129 µs ± 399 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [28]:
b = 2.**a

In [30]:
def f(x):
    return ( (1-x**2) + np.log(x/2.0) ) * np.exp(-x/0.5)

In [31]:
f(2.0)

-0.054946916666202536

In [33]:
y = f(a)

In [34]:
np.sum(y)

-174.03264039579742

In [35]:
sum(y)

-174.0326403957907

In [37]:
positions = np.random.randint(low=1, high=100, size=(5, 3))
positions

array([[ 5, 50, 89],
       [ 5, 27, 56],
       [67, 48, 48],
       [87, 62, 51],
       [17, 62, 90]])

### Questions

 1. With one line of code, compute the distance to the origin `(0, 0, 0)` for all points.
 2. Find the mean position of all points.

In [39]:
# Distance
distances = np.sum( positions**2, axis=1 )**0.5
print(distances)

[102.20567499  62.36986452  95.37819457 118.38074168 110.60289327]


In [41]:
# Mean
mean = np.mean(positions, axis=0)
print(mean)

[36.2 49.8 66.8]


## Broadcasting

In [44]:
# Broadcasting
d0 = np.array([1, 1, 1])
print(d0.shape, positions.shape)
new_positions = positions + d0
print(new_positions)

(3,) (5, 3)
[[ 6 51 90]
 [ 6 28 57]
 [68 49 49]
 [88 63 52]
 [18 63 91]]


In [52]:
a = np.arange(10).reshape(2,5)
b = np.array([10,20])
print(a)
print(b)
print()
print(a.shape, b.shape, b[:,np.newaxis].shape)
print()
print(b[:,np.newaxis])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[10 20]

(2, 5) (2,) (2, 1)

[[10]
 [20]]


In [53]:
a+b[:,np.newaxis]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [47]:
a+b

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

## Fancy indexing

In [55]:
# Fancy indexing
a = np.random.randint(low=1, high=100, size=10)

In [60]:
print(a)
print(a[2])
print(a[2:-1:2])
print(a[[1, 5, 7, 9]])
print()

idx = np.random.randint(low=0, high=9, size=(2, 5, 10))
print(idx)

[47 29 31 32 64 96 46 23 15  1]
31
[31 64 46 15]
[29 96 23  1]

[[[2 5 1 6 2 1 1 4 4 1]
  [3 4 8 4 8 2 0 7 1 6]
  [3 3 5 1 5 1 5 2 8 3]
  [8 7 6 2 6 7 1 1 0 2]
  [2 0 8 7 1 0 5 3 7 6]]

 [[2 1 6 0 6 2 0 3 6 4]
  [4 6 4 7 7 3 6 7 2 2]
  [0 1 7 3 7 0 8 8 0 1]
  [3 7 3 3 8 1 8 7 8 3]
  [8 4 5 6 8 3 6 8 7 5]]]


In [61]:
print(a[idx])

[[[31 96 29 46 31 29 29 64 64 29]
  [32 64 15 64 15 31 47 23 29 46]
  [32 32 96 29 96 29 96 31 15 32]
  [15 23 46 31 46 23 29 29 47 31]
  [31 47 15 23 29 47 96 32 23 46]]

 [[31 29 46 47 46 31 47 32 46 64]
  [64 46 64 23 23 32 46 23 31 31]
  [47 29 23 32 23 47 15 15 47 29]
  [32 23 32 32 15 29 15 23 15 32]
  [15 64 96 46 15 32 46 15 23 96]]]


In [62]:
a = np.random.randint(low=0, high=100, size=(5, 2, 3))

In [63]:
a

array([[[15,  8, 78],
        [59, 13, 31]],

       [[55, 14, 13],
        [92,  6, 50]],

       [[80, 30, 35],
        [96, 59,  9]],

       [[ 5, 38, 36],
        [90, 32, 28]],

       [[96,  4, 38],
        [ 4, 39, 73]]])

In [65]:
a[:, 0, :]

array([[15,  8, 78],
       [55, 14, 13],
       [80, 30, 35],
       [ 5, 38, 36],
       [96,  4, 38]])

### Questions

1. Compute the mean position between the two bees for all 5 pictures
2. Apply a mirror symmetry $x \to -x$ to the system

In [66]:
a

array([[[15,  8, 78],
        [59, 13, 31]],

       [[55, 14, 13],
        [92,  6, 50]],

       [[80, 30, 35],
        [96, 59,  9]],

       [[ 5, 38, 36],
        [90, 32, 28]],

       [[96,  4, 38],
        [ 4, 39, 73]]])

In [67]:
# m = (a[:, 0, :] + a[:, 1, :]) / 2
mean_bees = np.mean(a, axis=1)
print(mean_bees)

[[37.  10.5 54.5]
 [73.5 10.  31.5]
 [88.  44.5 22. ]
 [47.5 35.  32. ]
 [50.  21.5 55.5]]


In [68]:
a[..., 0] = -a[..., 0]
# identidcal to a[:,:, 0] = -a[:,:, 0]

In [69]:
a

array([[[-15,   8,  78],
        [-59,  13,  31]],

       [[-55,  14,  13],
        [-92,   6,  50]],

       [[-80,  30,  35],
        [-96,  59,   9]],

       [[ -5,  38,  36],
        [-90,  32,  28]],

       [[-96,   4,  38],
        [ -4,  39,  73]]])

In [70]:
a[:, ::-1, :]

array([[[-59,  13,  31],
        [-15,   8,  78]],

       [[-92,   6,  50],
        [-55,  14,  13]],

       [[-96,  59,   9],
        [-80,  30,  35]],

       [[-90,  32,  28],
        [ -5,  38,  36]],

       [[ -4,  39,  73],
        [-96,   4,  38]]])

In [71]:
# Mask
a = np.random.randint(low=-100, high=100, size=(5, 3))

In [72]:
a

array([[ -5,  19, -68],
       [ -7, -37, -20],
       [ 76, -71, -16],
       [ 98, -95, -17],
       [-47,  99,  40]])

In [73]:
condition = a>0

In [76]:
print(type(condition), condition.shape, condition.dtype)
print(condition)

<class 'numpy.ndarray'> (5, 3) bool
[[False  True False]
 [False False False]
 [ True False False]
 [ True False False]
 [False  True  True]]


In [77]:
a[condition] = 0
print(a)

[[ -5   0 -68]
 [ -7 -37 -20]
 [  0 -71 -16]
 [  0 -95 -17]
 [-47   0   0]]


In [80]:
print(a[~condition].shape)
print(a[~condition])

(10,)
[ -5 -68  -7 -37 -20 -71 -16 -95 -17 -47]
